--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: WWW-Mechanize-Cached
date: 1 Dec 2003
author: SPOON
version: 0.01
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  Test::Pod: 1.02
requires:
  Cache::Cache: 1.02
  Storable: 2.08
  WWW::Mechanize: 0.70

private:
  directory:
    - t

provides:
  WWW::Mechanize::Cached:
    file: lib/WWW/Mechanize/Cached.pm
    version: 1.23

dynamic_config: 0
generated_by: docmaker version 1.01
