---
abstract: 'Cache response to be polite'
author:
  - 'Iain Truskett (original author)'
  - 'Andy Lester <petdance@cpan.org> (2004 - July 2009)'
  - 'Olaf Alders <olaf@wundercounter.com> (current maintainer)'
build_requires:
  File::Spec: '0'
  Find::Lib: '0'
  HTTP::Request: '0'
  Module::Build: '0.28'
  Path::Class: '0'
  Test::More: '0'
  Test::Requires: '0'
  constant: '0'
  lib: '0'
  vars: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Mechanize-Cached
requires:
  CHI: '0'
  Cache::FileCache: '0'
  Carp: '0'
  Data::Dump: '0'
  Moose: '0'
  Storable: '2.21'
  WWW::Mechanize: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://github.com/oalders/www-mechanize-cached/issues
  homepage: https://github.com/oalders/www-mechanize-cached
  repository: https://github.com/oalders/www-mechanize-cached.git
version: '1.44'
x_contributors:
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Neil Bowers <neil@bowers.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
