--- #YAML:1.0
name:               WWW-Mechanize-Cached
version:            1.34
abstract:           Cache response to be polite
author:
    - Olaf Alders <olaf@wundercounter.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::Cache:    1.02
    Carp:            0
    Storable:        2.08
    Test::More:      0.47
    Test::Warn:      0.11
    WWW::Mechanize:  1.00
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
