---
abstract: 'Cache response to be polite'
author:
  - 'Iain Truskett (original author)'
  - 'Andy Lester <petdance@cpan.org> (2004 - July 2009)'
  - 'Olaf Alders <olaf@wundercounter.com> (current maintainer)'
build_requires:
  Devel::SimpleTrace: 0
  English: 0
  File::Spec: 0
  Find::Lib: 0
  HTTP::Request: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::More: 0
  constant: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mechanize-Cached
requires:
  Cache::FileCache: 0
  Carp: 0
  Data::Dump: 0
  Moose: 0
  Storable: 0
  WWW::Mechanize: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Mechanize-Cached
  repository: http://github.com/oalders/www-mechanize-cached
version: 1.38
